/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Feb 26 12:47:03 2019. */

#include "imumsg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t IMUInfo_fields[10] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, IMUInfo, acc_x, acc_x, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, acc_y, acc_x, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, IMUInfo, sensorID, acc_y, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, acc_z, sensorID, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, angular_x, acc_z, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, angular_y, angular_x, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, angular_z, angular_y, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, time_stamp, angular_z, 0),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, IMUInfo, isStamp, time_stamp, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
